
  ServerName tile.openmaps.fr 
  #For historical compatibility, this was, from 2010 up to 2025-10-12 the main tile URL :
  #(My goal during 2026 is to get rid of it ) :
  ServerAlias maps.refuges.info

  CustomLog /var/log/apache2/tile.openmaps.fr-access.log combined
  ErrorLog  /var/log/apache2/tile.openmaps.fr-error.log


  # If tile is missing, don't render it if past this load threshold (user gets 404 error) Adjust close to your CPU core's number, it will ensure load does not skyrocket.
  ModTileMaxLoadMissing 5

  ModTileEnableTileThrottling On
  ModTileThrottlingTiles 3000 0.5
  ModTileThrottlingRenders 1000 0.2


# Here comes the protection agains abuses, redirects, tile replacement
# Add Here some user Agent to deny (Note that a service apache2 reload is ok : don't need a restart cutting all connections)
<IfModule mod_rewrite.c>
  RewriteEngine on
  SSLProxyEngine On
  
  ##### HTTP 403 "access denied" without showing any type of tiles for clear abuse of fake user agent (like browser ghosting or the like)
  # With users beeing honest what they do, I tend to be much more gentle and start by displaying tiles with explanations, but for those faking user agent to try bypassing
  # restrictions, I won't.
  # eg : (Firefox/49.0|Iron Safari)
  RewriteCond %{HTTP_USER_AGENT}  ^.*(Firefox/49.0)$
  RewriteRule . - [R=403,L]

  ##### HTTP 200 WITH TILE : Showing information within at specialy crafted tiles retrieved from https://openmaps.fr/images/...
  # Multiple tiles are available with different text in english: restricted, limited, denied
  
  #This web URL does not exist anymore (that is a redirect, no one should have it as referer)
  RewriteCond %{HTTP_REFERER} ^https://maps\.refuges\.info [NC,OR]
  RewriteCond %{HTTP_REFERER} ^http://maps\.refuges\.info [NC]
  #There is nothing on the root of https://tile.openmaps.fr/ obviously faking referer
  RewriteCond %{HTTP_REFERER} ^https://tile\.openmaps\.fr [NC,OR]
  RewriteRule ^(.*)$ https://openmaps.fr/images/tile-access-denied-referer.png [P,L]
  
  #We don't accept empty referer, please make yourself identifiable
  RewriteCond %{HTTP_USER_AGENT} ^$ [NC]
  RewriteRule ^(.*)$ https://openmaps.fr/images/tile-access-denied-user-agent.png [P,L]

  #Generic User-Agent from default lib, showing "randomly" every 50 tiles a tile warning about non respect of Usage Policy, Please update your User Agent !
  RewriteCond %{HTTP_USER_AGENT} ^(okhttp.*|Apache-HttpClient.*|flutter_map|Mozilla/5.0)$ [NC]
  RewriteCond %{REQUEST_URI} .*1[1-9]/[0-9]*[05]\/[0-9]*[5]\.png$
  RewriteRule ^(.*)$ https://openmaps.fr/images/tile-limited-access-useragent.png [P,L]

  ##### HTTP 200 with special files (robots.txt favicons ...)
  RewriteRule ^.*robots.txt$ https://openmaps.fr/well-known-proxy/robots.txt [P,L]

  ##### HTTP 302 Root redirection
  # / of tile.openmaps.fr and maps.refuges.info is now a redirect to https://openmaps.fr a basic Openlayers / frontend
  RewriteRule "/$" https://openmaps.fr
  
  ##### HTTP 503 used internally by mod_tile for too much request of rendered tiles
  
</IfModule>
