server {
    listen 80;
    listen [::]:80;
    server_name stats.openmaps.fr;

    access_log /var/log/nginx/stats.openmaps.fr-access.log combined;
    error_log  /var/log/nginx/stats.openmaps.fr-error.log;

    root /home/sites/stats;

    location ~ \.(cgi|pl)$ {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
