############## tile.openmaps.fr (and old maps.refuges.info) for tile serving with mod_tile
# This file's goal is to provide both http and https accesses while factorising config for mod_tile
# Some apps still rely on http accesses, and providing tiles is not sensible data.
# After all, no harm in keeping http accesses, in some high latency network
# (mobility ?) it can even provide from 60ms to 200ms speed boost to retrieve a tile

# Most usage I know use https, but, in some legacy cases or mobility, there are usage for http version (faster in high latency network)
# And it is not that hard to copy/paste a few directives
<VirtualHost *:80>
  ServerName tile.openmaps.fr
  #For historical compatibility, this was, from 2010 up to 2025-10-12 the main tile URL
  #(My goal during 2026 is to get rid of it ) :
  ServerAlias maps.refuges.info

  CustomLog /var/log/apache2/tile.openmaps.fr-access.log combined
  ErrorLog  /var/log/apache2/tile.openmaps.fr-error.log

  Include common-for-tiles.conf
  ModTileEnableTileThrottling On
  ModTileThrottlingTiles 4000 0.5
  ModTileThrottlingRenders 1000 0.2
  ModTileEnableTileThrottlingXForward 0
</VirtualHost>

<VirtualHost *:443>
  ServerName tile.openmaps.fr 
  #For historical compatibility, this was, from 2010 up to 2025-10-12 the main tile URL :
  #(My goal during 2026 is to get rid of it ) :
  ServerAlias maps.refuges.info

  CustomLog /var/log/apache2/tile.openmaps.fr-access.log combined
  ErrorLog  /var/log/apache2/tile.openmaps.fr-error.log

  SSLEngine       On
  SSLCertificateFile      /etc/letsencrypt/live/tile.openmaps.fr/cert.pem
  SSLCertificateKeyFile   /etc/letsencrypt/live/tile.openmaps.fr/privkey.pem
  SSLCertificateChainFile /etc/letsencrypt/live/tile.openmaps.fr/fullchain.pem

  Include common-for-tiles.conf
  ModTileEnableTileThrottling On
  ModTileThrottlingTiles 4000 0.5
  ModTileThrottlingRenders 1000 0.2
  ModTileEnableTileThrottlingXForward 0
</VirtualHost>

