############## tile.openmaps.fr (and old maps.refuges.info) for tile serving with mod_tile
# This file's goal is to provide both http and https accesses while factorising config for mod_tile
# Some apps still rely on http accesses, and providing tiles is not sensible data.
# After all, no harm in keeping http accesses, in some high latency network
# (mobility ?) it can even provide from 60ms to 200ms speed boost to retrieve a tile

# Most usage I know use https, but, in some legacy cases or mobility, there are usage for http version (faster in high latency network)
# And it is not that hard to copy/paste a few directives
<VirtualHost *:80>
  Include common-for-tile.openmaps.fr.conf
  Include common-for-tiles.conf
</VirtualHost>

<VirtualHost *:443>
  Include common-for-tile.openmaps.fr.conf
  Include common-for-tiles.conf

  SSLEngine       On
  SSLCertificateFile      /etc/letsencrypt/live/tile.openmaps.fr/cert.pem
  SSLCertificateKeyFile   /etc/letsencrypt/live/tile.openmaps.fr/privkey.pem
  SSLCertificateChainFile /etc/letsencrypt/live/tile.openmaps.fr/fullchain.pem
</VirtualHost>

